Repository clusterlink-net/clusterlink, pull requests merged in 2023-11, with the labels that each got.

#148 Update for OpenSpeedTest application demo
  demos/speedtest/kind/README.md
  demos/speedtest/kind/apply_policy.py
  demos/speedtest/kind/service_import.py
  demos/speedtest/kind/test.py
  demos/speedtest/testdata/manifests/firefox.yaml
  demos/speedtest/testdata/manifests/firefox2.yaml
  demos/speedtest/testdata/manifests/speedtest.yaml
  demos/speedtest/testdata/policy/denyFromGw.json
  demos/speedtest/testdata/policy/denyToSpeedtest.json
Labels: size/L

#146 dataplane: Reduce xDS client connect timeout
  pkg/dataplane/client/xds.go
Labels: size/XS, go-dataplane

#155 dataplane/server: Fix HTTP status check
  pkg/dataplane/server/server.go
Labels: size/XS

#150 demos/bookinfo: Update for BookInfo application demo
  Makefile
  demos/bookinfo/kind/README.md
  demos/bookinfo/kind/apply_lb.py
  demos/bookinfo/kind/gw_failover.py
  demos/bookinfo/kind/mbg_failover.py
  demos/bookinfo/kind/test.py
  docs/figures/BookInfo_demo.png
Labels: size/XL

#157 Enable and disable peers in the policy engine
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/loadBalancer.go
Labels: size/L

#158 controlplane/authz: Add source service to a connection request to the policy engine
  pkg/controlplane/authz.go
Labels: size/XS

#156 Add peer authorization check to ingress connection
  demos/speedtest/kind/service_import.py
  demos/speedtest/kind/test.py
  pkg/controlplane/authz.go
  pkg/controlplane/server/http/authz.go
Labels: size/S

#149 Update the iPerf3 README file
  demos/iperf3/kind/README.md
  demos/iperf3/kind/simple_test.py
  demos/iperf3/testdata/manifests/iperf3-server/iperf3.yaml
  demos/utils/common.py
  demos/utils/kind.py
  demos/utils/manifests/kind/cl-svc.yaml
Labels: size/L

#111 Introduce e2e Kubernetes test suite
  .github/workflows/pr-e2e-test.yml
  Makefile
  go.mod
  go.sum
  pkg/bootstrap/platform/k8s.go
  tests/e2e/connectivity/basic_test.go
  tests/e2e/iperf3/iperf3_test.go
  tests/e2e/k8s/k8s_test.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_performance.go
  tests/e2e/k8s/util/async.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
  tests/e2e/k8s/util/kind.go
  tests/e2e/k8s/util/policies.go
  tests/e2e/utils/common.go
  tests/e2e/utils/kind.go
  tests/e2e/utils/testdata/manifests/curl-client.yaml
  tests/e2e/utils/testdata/manifests/iperf3/iperf3-client.yaml
  tests/e2e/utils/testdata/manifests/iperf3/iperf3-server.yaml
  tests/e2e/utils/testdata/manifests/pinger-server.yaml
  tests/e2e/utils/testdata/policy/allowAll.json
Labels: size/XXL

#159 controlplane/api/authz: Change client IP header
  cmd/cl-dataplane/app/envoyconf.go
  pkg/controlplane/api/authz.go
Labels: size/XS

#142 Clean-up README file
  README.md
Labels: size/M

#162 Support for dev-container
  .devcontainer/devcontainer.json
  .gitignore
  .licenserc.yaml
  Containerfile.dev
  Makefile
  hack/install-devtools.sh
Labels: size/L

#167 cmd/cl-adm: Add log-level flag
  cmd/cl-adm/cmd/create/create_peer.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/M

#171 Add `-v` / `--version` to executables
  Makefile
  cmd/cl-controlplane/cl-controlplane.go
  cmd/cl-dataplane/cl-dataplane.go
  cmd/cl-go-dataplane/cl-go-dataplane.go
  cmd/gwctl/main.go
  pkg/versioninfo/variables.go
  pkg/versioninfo/version.go
  pkg/versioninfo/version.txt
Labels: size/L

#176 cmd/cl-adm: Add container registry flag
  cmd/cl-adm/cmd/create/create_peer.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/M

#164 Move the utils function for the demos to be under the cluster class.
  demos/bookinfo/kind/apply_lb.py
  demos/bookinfo/kind/gw_failover.py
  demos/bookinfo/kind/test.py
  demos/bookinfo/test.py
  demos/iperf3/kind/iperf3_client_start.py
  demos/iperf3/kind/simple_test.py
  demos/iperf3/kind/test.py
  demos/iperf3/test.py
  demos/qotd/kind/test.py
  demos/speedtest/cloud/test.py
  demos/speedtest/kind/apply_policy.py
  demos/speedtest/kind/service_import.py
  demos/speedtest/kind/test.py
  demos/utils/common.py
  demos/utils/k8s.py
  demos/utils/kind.py
  demos/utils/manifests/kind/flannel/flannel-config.yaml
Labels: size/XXL

#179 Review and amend open source files
  CONTRIBUTING.md
  README.md
Labels: documentation, size/S

#175 dataplane/server/listener: Close socket on error
  pkg/dataplane/server/listener.go
Labels: bug, size/XS, go-dataplane

#178 controlplane: connect enable/disable peer to heartbeat
  pkg/controlplane/authz.go
  pkg/controlplane/client.go
  pkg/controlplane/instance.go
Labels: size/M

#182 tests/e2e/k8s: Allow timeout errors
  tests/e2e/k8s/util/clusterlink.go
Labels: size/XS

#183 Remove mbg manifests
  config/manifests/gwctl/gwctl-cloud.yaml
  config/manifests/gwctl/gwctl.yaml
  config/manifests/mbg/dataplane.yaml
  config/manifests/mbg/mbg-cloud.yaml
  config/manifests/mbg/mbg-role.yaml
  config/manifests/mbg/mbg.yaml
Labels: size/L

#188 Devcontainer fixes
  .gitignore
  Makefile
  hack/install-devtools.sh
Labels: size/M

#185 demos/bookinfo: Fix the failover scenario
  demos/bookinfo/cloud/gw_failover.py
  demos/bookinfo/kind/gw_failover.py
  demos/bookinfo/test.py
Labels: size/S

#190 controlplane/server: Fix list() return value
  pkg/controlplane/server/http/api.go
Labels: size/XS

#189 Initial landing page
  .licenserc.yaml
  website/.gitignore
  website/assets/scss/_variables_project.scss
  website/content/en/_index.md
  website/go.mod
  website/go.sum
  website/hugo.toml
  website/static/clusterlink.png
Labels: size/L

#191 cmd/gwctl: Add update subcommand
  cmd/gwctl/main.go
  cmd/gwctl/subcommand/export.go
  cmd/gwctl/subcommand/import.go
  cmd/gwctl/subcommand/peer.go
  cmd/gwctl/subcommand/policy.go
Labels: size/L

#193 Deploy to Netlify
  netlify.toml
  website/package.json
Labels: size/S

#199 Website preview
  .licenserc.yaml
  website/assets/icons/logo.png
  website/assets/icons/logo.svg
  website/assets/scss/_variables_project.scss
  website/content/en/_index.md
  website/content/en/docs/_index.md
  website/content/en/docs/doc-contribution/_index.md
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/overview/_index.md
  website/content/en/docs/reference/_index.md
  website/content/en/docs/tasks/_index.md
  website/content/en/docs/tasks/fabric.md
  website/content/en/docs/tasks/policies.md
  website/content/en/docs/tasks/services.md
  website/content/en/docs/tasks/site.md
  website/content/en/docs/tutorials/_index.md
  website/static/clusterlink.png
  website/static/favicons/favicon.ico
  website/static/favicons/favicon.png
  website/static/favicons/favicon.svg
Labels: size/L

#205 Tweak the top navbar
  website/assets/icons/logo.svg
  website/hugo.toml
Labels: size/XS

#172 cmd/cl-dataplane: Increasing Envoy's max_outbound_frames
  cmd/cl-dataplane/app/envoyconf.go
Labels: size/XS

#184 docs: Installation Guide for ClusterLink
  README.md
  demos/iperf3/kind/README.md
  docs/installation.md
Labels: size/L

#209 Landing page tweaks
  website/content/en/_index.md
  website/content/en/about/_index.md
  website/content/en/docs/_index.md
  website/content/en/docs/concepts/_index.md
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/policies.md
  website/content/en/docs/concepts/services.md
  website/content/en/docs/concepts/site.md
  website/content/en/featured-background.jpg
  website/content/en/search.md
  website/hugo.toml
Labels: documentation, size/M

#206 .github/workflows: Create docker release and publish it to ghcr
  .github/workflows/make-release.yml
  Makefile
Labels: size/M

#208 demos/utils: Disable kind creation in the background for a non-default CNI
  demos/utils/kind.py
Labels: size/XS

#213 controlplane: Return 404 on object not found
  pkg/controlplane/instance.go
  pkg/controlplane/server/http/api.go
  pkg/util/rest/server.go
Labels: size/S

#211 controlplane: Make policies deletable by name
  cmd/gwctl/subcommand/policy.go
  pkg/controlplane/instance.go
  pkg/controlplane/server/http/api.go
Labels: size/M

#212 policyengine: Don't remove bindings of a deleted peer
  pkg/controlplane/instance.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
Labels: size/M

#216 controlplane: Return 404 on bindings not found
  pkg/controlplane/server/http/api.go
Labels: size/XS

#198 pkg/platform: Fix update and external service for k8s platform
  Makefile
  cmd/gwctl/subcommand/export.go
  pkg/api/types.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/instance.go
  pkg/platform/k8s/platform.go
  pkg/platform/k8s/reconciler.go
  pkg/platform/platform.go
  pkg/platform/unknown/platform.go
  pkg/utils/netutils/netutils.go
Labels: size/L

#219 pkg/dataplane/server: Change ingress connection setup order
  pkg/dataplane/server/server.go
Labels: size/S

#217 tests/e2e/k8s: Add controlplane CRUD test
  tests/e2e/k8s/services/errors.go
  tests/e2e/k8s/services/httpecho/client.go
  tests/e2e/k8s/services/httpecho/server.go
  tests/e2e/k8s/services/iperf3/client.go
  tests/e2e/k8s/services/iperf3/server.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_performance.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
  tests/e2e/k8s/util/kind.go
Labels: size/XXL

#220 dataplane/server: Add timeout for service dialing
  pkg/dataplane/server/server.go
Labels: size/XS
