Repository clusterlink-net/clusterlink, pull requests merged in 2023-10, with the labels that each got.

#60 cicd: Enable additional linters
  .golangci.yaml
  Makefile
  pkg/controlplane/store/store.go
  pkg/k8s/kubernetes/kubeinformer.go
  pkg/metrics/metrics.go
  pkg/policyengine/accessControl.go
  pkg/util/jsonapi/client.go
Labels: cicd

#74 .github/workflows: Fix various errors runnning golangci-lint
  .github/workflows/pr-check.yml
Labels: bug, cicd

#88 tests/k8s.sh: Move iperf server to a new pod
  tests/k8s.sh
Labels: size/S

#58 Custom Go-based dataplane for xDS control plane APIs
  .github/workflows/pr-e2e-test.yml
  Makefile
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-adm/templates/config.go
  cmd/cl-adm/templates/docker.go
  cmd/cl-adm/templates/k8s.go
  cmd/cl-go-dataplane/Dockerfile
  cmd/cl-go-dataplane/app/server.go
  cmd/cl-go-dataplane/cl-go-dataplane.go
  cmd/dataplane/main.go
  pkg/dataplane/client/fetcher.go
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/dataplane.go
  pkg/dataplane/server/forwarder.go
  pkg/dataplane/server/listener.go
  pkg/dataplane/server/server.go
  tests/docker.sh
  tests/k8s.sh
Labels: size/XL

#92 .github/workflows: add timeout to e2e tests
  .github/workflows/pr-e2e-test.yml
Labels: size/XS

#55 tests/iperf3 : support new control plane for k8s tests
  Makefile
  tests/e2e/connectivity/basic_test.go
  tests/e2e/iperf3/iperf3_test.go
  tests/e2e/utils/common.go
  tests/e2e/utils/kind.go
Labels: size/L

#97 Fix failing volume mount in "make copr-fix"
  Makefile
Labels: size/XS

#98 cmd/cl-adm: Fix bug that disables envoy use
  cmd/cl-adm/templates/config.go
Labels: size/XS

#95 Delete support for old controlplane in policy engine
  cmd/controlplane/subcommand/start.go
  pkg/client/client.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/accessControl.go
  pkg/policyengine/loadBalancer.go
  tests/e2e/connectivity/basic_test.go
Labels: size/XL

#109 controlplane, dataplane: Remove old controlplane and dataplane
  Makefile
  cmd/controlplane/main.go
  cmd/controlplane/subcommand/get.go
  cmd/controlplane/subcommand/start.go
  cmd/dataplane/main.go
  dockerfile
  go.mod
  go.sum
  pkg/controlplane/api/object/objects.go
  pkg/controlplane/binding.go
  pkg/controlplane/eventmanager/eventHandler.go
  pkg/controlplane/export.go
  pkg/controlplane/health/healthMonitor.go
  pkg/controlplane/import.go
  pkg/controlplane/peer.go
  pkg/controlplane/route.go
  pkg/controlplane/store/store.go
  pkg/dataplane/dataplane.go
  pkg/dataplane/mtls_forwarder.go
  pkg/dataplane/server.go
  pkg/dataplane/store/store.go
  pkg/dataplane/tcp_forwarder.go
  pkg/utils/httputils/httputils.go
Labels: size/XXL

#104 platform/k8s: Support GetLabelsFromIP
  cmd/cl-adm/templates/k8s.go
  go.mod
  go.sum
  pkg/platform/k8s/platform.go
  pkg/platform/k8s/pod_reconciler.go
  pkg/platform/k8s/pod_reconciler_test.go
  pkg/platform/platform.go
  pkg/platform/unknown/platform.go
Labels: size/L

#110 tests/e2e: Remove MBG acronym and old controlplane from e2e tests
  tests/e2e/connectivity/basic_test.go
  tests/e2e/iperf3/iperf3_test.go
  tests/e2e/utils/common.go
  tests/e2e/utils/kind.go
  tests/e2e/utils/testdata/manifests/dataplane.yaml
  tests/e2e/utils/testdata/manifests/mbg-role.yaml
  tests/e2e/utils/testdata/manifests/mbg.yaml
  tests/e2e/utils/testdata/mtls/ca.crt
  tests/e2e/utils/testdata/mtls/ca.key
  tests/e2e/utils/testdata/mtls/mbg1.crt
  tests/e2e/utils/testdata/mtls/mbg1.csr
  tests/e2e/utils/testdata/mtls/mbg1.key
  tests/e2e/utils/testdata/mtls/mbg2.crt
  tests/e2e/utils/testdata/mtls/mbg2.csr
  tests/e2e/utils/testdata/mtls/mbg2.key
Labels: size/XL

#108 Run CI jobs in parallel; run CI jobs after merging to main
  .github/workflows/pr-check.yml
  .github/workflows/pr-e2e-test.yml
Labels: size/S

#113 Activating dependabot to automatically update project dependencies
  .github/dependabot.yml
Labels: size/S

#107 Adding CodeQL - security code scanner
  .github/workflows/codeql.yml
Labels: size/M

#103 Fix timing issue on go dataplane startup
  .github/workflows/pr-e2e-test.yml
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/listener.go
  tests/k8s.sh
Labels: size/M

#114 Loadbalancer cleanup before integration with new controlplane
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
Labels: size/L

#125 pkg/platform/k8s: Add locking to multi-threaded maps
  pkg/platform/k8s/pod_reconciler.go
Labels: bug, size/S

#123 Loadbalancer integration into new controlplane
  cmd/gwctl/subcommand/policy.go
  pkg/client/client.go
  pkg/controlplane/instance.go
  pkg/controlplane/server/http/api.go
  pkg/controlplane/store/lbpolicies.go
  pkg/controlplane/store/types.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
  tests/e2e/connectivity/basic_test.go
  tests/e2e/iperf3/iperf3_test.go
Labels: size/XL

#129 Wrap errors correctly
  .golangci.yaml
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-adm/templates/docker.go
  cmd/cl-adm/templates/k8s.go
  cmd/cl-dataplane/app/envoy.go
  cmd/cl-dataplane/app/server.go
  cmd/cl-go-dataplane/app/server.go
  cmd/gwctl/subcommand/gwctl.go
  pkg/controlplane/authz.go
  pkg/controlplane/client.go
  pkg/controlplane/instance.go
  pkg/controlplane/server/controller.go
  pkg/controlplane/server/http/api.go
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/server.go
  pkg/store/kv/bolt/store.go
  pkg/store/kv/store.go
  pkg/util/jsonapi/client.go
  pkg/util/log/log.go
  pkg/util/rest/client.go
  pkg/util/tls.go
  tests/e2e/utils/kind.go
  tests/k8s.sh
Labels: size/L

#99 cmd/cl-adm: Move core logic to a separate package
  cmd/cl-adm/cmd/create/create_fabric.go
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-adm/templates/config.go
  cmd/cl-adm/templates/docker.go
  pkg/bootstrap/cert.go
  pkg/bootstrap/crypt.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  tests/docker.sh
Labels: size/XL

#130 Remove files for demo package
  demos/iperf3/bare-metal/commands.txt
  demos/iperf3/bare-metal/genkeys.sh
  demos/iperf3/bare-metal/openssl.cnf
  demos/iperf3/bare-metal/testservice.go
  demos/utils/getMbgLocalPort.py
  demos/utils/manifests/kind/mbg-config1.yaml
  demos/utils/manifests/kind/mbg-config2.yaml
  demos/utils/manifests/kind/mbg-config3.yaml
  demos/utils/mtls/ca.crt
  demos/utils/mtls/ca.key
  demos/utils/mtls/ca.srl
  demos/utils/mtls/gen.py
  demos/utils/mtls/mbg1.crt
  demos/utils/mtls/mbg1.csr
  demos/utils/mtls/mbg1.key
  demos/utils/mtls/mbg2.crt
  demos/utils/mtls/mbg2.csr
  demos/utils/mtls/mbg2.key
  demos/utils/mtls/mbg3.crt
  demos/utils/mtls/mbg3.csr
  demos/utils/mtls/mbg3.key
Labels: size/XL

#134 Group multiple dependencies in dependabot PRs
  .github/dependabot.yml
Labels: size/S

#131 Simpler and shorter Contribution Guide
  CONTRIBUTING.md
Labels: size/L

#132 Fix CodeQL security warnings.
  cmd/gwctl/subcommand/export.go
  pkg/controlplane/authz.go
Labels: size/XS

#139 Support new controlplane for iPerf3 Demo
  demos/iperf3/kind/iperf3_client_start.py
  demos/iperf3/kind/simple_test.py
  demos/utils/common.py
  demos/utils/k8s.py
  demos/utils/kind.py
  demos/utils/kind/kindAux.py
  demos/utils/mbgAux.py
Labels: size/XL

#145 platform/k8s: Enable controller-runtime logging
  go.mod
  go.sum
  pkg/platform/k8s/platform.go
Labels: bug, size/XS, platform/k8s

#147 demos/iperf3: Remove allinone files for iperf3 tests
  demos/iperf3/kind/allinone.py
  demos/iperf3/kind/apply_policy.py
  demos/iperf3/kind/connect_mbgs.py
  demos/iperf3/kind/iperf3_external_service.py
  demos/iperf3/kind/iperf3_service_create.py
  demos/iperf3/kind/iperf3_service_get.py
  demos/iperf3/kind/iperf3_service_import.py
  demos/iperf3/kind/start_cluster_mbg.py
  demos/iperf3/testdata/policy/denyFromGw.json
  demos/iperf3/testdata/policy/denyToIperf3.json
Labels: size/XL

#152 util/sniproxy: Reduce dial timeout
  pkg/util/sniproxy/server.go
Labels: size/XS

#151 demos/qotd: Update for QotD application demo
  demos/qotd/kind/test.py
Labels: size/L
