Repository clusterlink-net/clusterlink, pull requests merged in 2024-03, with the labels that each got.

#364 cl-dataplane: Disable controlplane TLS session keys
  cmd/cl-dataplane/app/envoyconf.go
Labels: size/XS

#357 controlplane/rest: Introduce manager
  cmd/cl-controlplane/app/server.go
  pkg/controlplane/instance.go
  pkg/controlplane/rest/accesspolicy.go
  pkg/controlplane/rest/binding.go
  pkg/controlplane/rest/export.go
  pkg/controlplane/rest/import.go
  pkg/controlplane/rest/lbpolicy.go
  pkg/controlplane/rest/manager.go
  pkg/controlplane/rest/peer.go
  pkg/controlplane/rest/server.go
Labels: size/XXL

#373 controlplane/control: Delete ports by name
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/port.go
  pkg/controlplane/rest/import.go
Labels: size/M

#361 controlplane/control: Introduce peer manager
  cmd/cl-controlplane/app/server.go
  config/crds/clusterlink.net_peers.yaml
  config/operator/rbac/role.yaml
  go.mod
  go.sum
  pkg/apis/clusterlink.net/v1alpha1/peer.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/peer.go
  pkg/controlplane/peer/client.go
  pkg/controlplane/rest/peer.go
  pkg/operator/controller/instance_controller.go
Labels: size/XL

#374 Makefile: Remove unused targets
  Makefile
Labels: size/S

#360 Support remove/update operations in go dataplane
  pkg/dataplane/client/fetcher.go
  pkg/dataplane/server/dataplane.go
  pkg/dataplane/server/listener.go
  tests/e2e/k8s/test_basic.go
Labels: size/L

#370 Release: Introduce GitHub Action for the release and installation script.
  .github/workflows/make-release.yml
  .github/workflows/release.yml
  Makefile
  cmd/cl-adm/cl-adm.go
  hack/install_clusterlink.sh
  pkg/versioninfo/variables.go
  pkg/versioninfo/version.go
  pkg/versioninfo/version.txt
  website/content/en/docs/getting-started/_index.md
Labels: size/L

#379 restructure getting-started guides
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/getting-started/developers.md
  website/content/en/docs/getting-started/users.md
Labels: size/L

#380 versioninfo: Adding version info to operator and controller logs
  Makefile
  cmd/cl-controlplane/app/server.go
  cmd/cl-operator/main.go
  pkg/versioninfo/variables.go
Labels: size/S

#381 cmd/deploy: Support container registry flag in deploy peer command.
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-adm/cmd/deploy/deploy_peer.go
  cmd/cl-adm/config/config.go
  config/operator/manager/manager.yaml
Labels: size/M

#382 cmd/deploy: Support ingress port flag
  cmd/cl-adm/cmd/deploy/deploy_peer.go
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  pkg/operator/controller/instance_controller.go
Labels: size/M

#376 pkg/api: Move bindings inside imports
  cmd/gwctl/main.go
  cmd/gwctl/subcommand/binding.go
  cmd/gwctl/subcommand/gwctl.go
  cmd/gwctl/subcommand/import.go
  demos/bookinfo/test.py
  demos/iperf3/kind/README.md
  demos/iperf3/test.py
  demos/qotd/kind/test.py
  demos/speedtest/kind/service_import.py
  pkg/api/types.go
  pkg/client/client.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/rest/binding.go
  pkg/controlplane/rest/import.go
  pkg/controlplane/rest/manager.go
  pkg/controlplane/rest/server.go
  pkg/controlplane/store/bindings.go
  pkg/controlplane/store/types.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/test_performance.go
  tests/e2e/k8s/util/clusterlink.go
  tests/k8s.sh
Labels: size/XXL

#386 .github/workflows: Add write permission to release workflow
  .github/workflows/release.yml
Labels: size/XS

#389 cmd/cl-controlplane: Move peer crd to be used only in CRD mode
  cmd/cl-controlplane/app/server.go
Labels: size/S

#403 cl-adm: add version flag to CLI
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-adm/cmd/deploy/deploy_peer.go
  config/crds/clusterlink.net_instances.yaml
  design-proposals/project-deploymnet.md
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  pkg/operator/controller/instance_controller.go
  pkg/operator/controller/instance_controller_test.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/M

#388 controlplane/control: Add export status updates
  config/crds/clusterlink.net_exports.yaml
  config/operator/rbac/role.yaml
  pkg/apis/clusterlink.net/v1alpha1/export.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/authz/controllers.go
  pkg/controlplane/control/controllers.go
  pkg/controlplane/control/manager.go
  pkg/operator/controller/instance_controller.go
Labels: size/L

#402 Enable custom website domain (clusterlink.net) with hugo and netlify
  website/config.toml
  website/content/en/docs/doc-contribution/_index.md
  website/netlify.toml
Labels: size/S

#405 tests/e2e/k8s: Fix dataplane log-level setting
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/XS

#407 pkg/api: Switch to v1alpha1.Export
  cmd/gwctl/subcommand/export.go
  pkg/api/types.go
  pkg/client/client.go
  pkg/controlplane/rest/export.go
  pkg/controlplane/store/types.go
  pkg/policyengine/PolicyDispatcher.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/test_performance.go
  tests/e2e/k8s/util/clusterlink.go
Labels: size/L

#383 controlplane/control: Support imports from all namespaces
  cmd/cl-controlplane/app/server.go
  config/crds/clusterlink.net_imports.yaml
  config/operator/rbac/role.yaml
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/port.go
  pkg/controlplane/xds/manager.go
  pkg/operator/controller/instance_controller.go
Labels: size/XL

#409 pkg/api: Switch to v1alpha1.Peer
  cmd/gwctl/subcommand/peer.go
  pkg/api/types.go
  pkg/client/client.go
  pkg/controlplane/rest/peer.go
  pkg/controlplane/store/types.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/util/clusterlink.go
Labels: size/L

#413 apis/import: Fix json names
  config/crds/clusterlink.net_imports.yaml
  pkg/apis/clusterlink.net/v1alpha1/import.go
Labels: size/S

#411 pkg/api: Switch to v1alpha1.Import
  cmd/gwctl/subcommand/import.go
  pkg/api/types.go
  pkg/client/client.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/rest/import.go
  pkg/controlplane/store/types.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/util/clusterlink.go
Labels: size/L

#390 supporting Import CRD in policyengine
  config/crds/clusterlink.net_imports.yaml
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/controlplane/authz/manager.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
  pkg/policyengine/policytypes/connection_request.go
  tests/e2e/k8s/test_basic.go
Labels: size/XL

#415 Complete draft of developer getting started guide
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/getting-started/developers.md
  website/content/en/docs/overview/_index.md
Labels: size/M

#417 [website] Move menu items to _index.md front matter
  website/config.toml
  website/content/en/about/_index.md
  website/content/en/docs/_index.md
Labels: documentation, size/S

#418 [website] Add blog collection and sample entry
  website/content/en/blog/_index.md
  website/content/en/blog/hello.md
Labels: documentation, size/M

#414 Complete governance document
  GOVERNANCE.md
Labels: documentation, size/L

#421 v1alpha1/import: Set Round-Robin as the default LBScheme
  cmd/gwctl/subcommand/policy.go
  config/crds/clusterlink.net_imports.yaml
  demos/bookinfo/cloud/apply_lb.py
  demos/bookinfo/kind/README.md
  demos/bookinfo/kind/apply_lb.py
  demos/bookinfo/test.py
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
Labels: size/L

#419 operator/controller: Update the operator to support only CRD mode
  pkg/operator/controller/instance_controller.go
  tests/e2e/k8s/test_operator.go
Labels: size/S

#422 tests/e2e/k8s: Set CRD mode as default
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/test_performance.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/S

#426 controlplane/control: Use shorter system service names
  go.mod
  pkg/controlplane/control/manager.go
Labels: size/S

#425 Change install path for root user
  hack/install_clusterlink.sh
Labels: size/XS

#430 Makefile: Change ENVTEST_VERSION
  Makefile
Labels: size/XS

#406 policyengine: Remove ConnectivityPolicy
  cmd/gwctl/subcommand/import.go
  demos/bookinfo/test.py
  demos/iperf3/cloud/test.py
  demos/iperf3/kind/README.md
  demos/iperf3/test.py
  demos/qotd/kind/test.py
  demos/speedtest/kind/service_import.py
  pkg/apis/clusterlink.net/v1alpha1/accesspolicy.go
  pkg/apis/clusterlink.net/v1alpha1/accesspolicy_test.go
  pkg/controlplane/authz/manager.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/connectivitypdp/connection_request.go
  pkg/policyengine/connectivitypdp/connectivity_pdp.go
  pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
  pkg/policyengine/connectivitypdp/test_data/all_layers.yaml
  pkg/policyengine/examples/allowAll.json
  pkg/policyengine/examples/allowToReviews.json
  pkg/policyengine/examples/deny_from_gw1.json
  pkg/policyengine/k8sshim/connectivity_policy_crd.go
  pkg/policyengine/k8sshim/connectivity_policy_crd_test.go
  pkg/policyengine/k8sshim/test_data/simple_privileged.yaml
  pkg/policyengine/policytypes/connectivity_policy.go
  pkg/policyengine/policytypes/connectivity_policy_test.go
  pkg/policyengine/policytypes/examples/allowAll.json
  pkg/policyengine/policytypes/examples/allowToReviews.json
  pkg/policyengine/policytypes/examples/deny_from_gw1.json
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/test_performance.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/policies.go
  tests/k8s.sh
Labels: size/XXL

#436 [website] Add makefile targets for website
  website/Makefile
Labels: size/S

#439 inet.af was hijacked and repo moved to github
  go.mod
  go.sum
  pkg/util/sniproxy/server.go
Labels: size/XS

#429 controlplane/authz: use policyengine response fields for connection request
  pkg/controlplane/authz/manager.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/connectivitypdp/connection_request.go
  tests/e2e/k8s/test_basic.go
Labels: size/M

#438 [website] latest docsy changes default ui param
  website/config.toml
Labels: size/XS

#444 Typo in project-deployment file name
  design-proposals/project-deployment.md
  website/content/en/docs/getting-started/users.md
Labels: size/XS

#435 check links action
  .github/workflows/linkcheck.yml
Labels: size/S

#440 Set gofumpt version to 0.6.0 instead of latest
  .devcontainer/dev/post-create.sh
  hack/install-devtools.sh
Labels: size/XS

#447 Reference `peer` instead of `site` in documentation
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/peers.md
  website/content/en/docs/concepts/policies.md
  website/content/en/docs/tutorials/iperf.md
Labels: size/M, ignore-for-release

#452 Additional documentation for tests and PRs
  website/content/en/docs/getting-started/developers.md
Labels: documentation, size/S

#441 cl-adm/cmd: rename "cl-adm" CLI to "clusterlink".
  Makefile
  cmd/clusterlink/cl-adm.go
  cmd/clusterlink/cmd/cmd.go
  cmd/clusterlink/cmd/create/create.go
  cmd/clusterlink/cmd/create/create_fabric.go
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/deploy/deploy.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  cmd/clusterlink/config/config.go
  demos/iperf3/kind/README.md
  demos/utils/common.py
  design-proposals/crd-based-management.md
  design-proposals/project-deployment.md
  docs/installation.md
  hack/install_clusterlink.sh
  tests/e2e/k8s/suite.go
  tests/k8s.sh
  website/content/en/docs/getting-started/users.md
Labels: size/L

#455 controlplane/control: Fix bug in peer status setting
  pkg/controlplane/control/peer.go
Labels: size/XS, bugfix

#457 controlplane/xds: Support multiple peer gateways
  pkg/controlplane/xds/manager.go
Labels: enhancement, size/XS

#451 controlplane/control: Bug fixes
  pkg/controlplane/control/manager.go
Labels: size/M, bugfix

#454 controlplane/control: Change heartbeat strategy
  go.mod
  go.sum
  pkg/controlplane/control/peer.go
Labels: enhancement, size/M

#433 [website] "hello world" blog entry
  website/config.toml
  website/content/en/blog/hello-world/index.md
  website/content/en/blog/hello-world/sunflower.jpg
  website/content/en/blog/hello.md
  website/netlify.toml
Labels: size/L

#467 Minor wording adjustment in "hello world" blog
  website/content/en/blog/hello-world/index.md
Labels: size/XS

#462 controlplane/control: Fix interval while peer is unhealthy
  pkg/controlplane/control/peer.go
Labels: size/XS, controlplane, bugfix

#468 cmd/clusterlink: Add fabric name to CLI
  cmd/clusterlink/cmd/create/create_fabric.go
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  cmd/clusterlink/config/config.go
  demos/utils/common.py
  pkg/bootstrap/cert.go
  tests/e2e/k8s/util/fabric.go
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/peers.md
  website/content/en/docs/getting-started/users.md
Labels: size/L

#470 controlplane/control: Fix updating of peer monitor
  pkg/controlplane/control/peer.go
Labels: size/S, controlplane, bugfix

#458 tests/e2e/k8s: Add more CRD-mode tests
  pkg/controlplane/control/manager.go
  tests/e2e/k8s/test_export.go
  tests/e2e/k8s/test_import.go
  tests/e2e/k8s/test_peer.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/kind.go
Labels: size/XL, tests

#431 policyengine/PolicyDispatcher: allow to delete unprivileged policy
  pkg/controlplane/authz/controllers.go
  pkg/controlplane/authz/manager.go
Labels: size/S

#461 Demos: Change the demos to support CRD mode
  Makefile
  demos/bookinfo/cloud/apply_lb.py
  demos/bookinfo/cloud/gw_failover.py
  demos/bookinfo/cloud/test.py
  demos/bookinfo/kind/apply_lb.py
  demos/bookinfo/kind/gw_failover.py
  demos/bookinfo/kind/test.py
  demos/bookinfo/test.py
  demos/iperf3/cloud/test.py
  demos/iperf3/kind/test.py
  demos/iperf3/test.py
  demos/qotd/kind/test.py
  demos/qotd/manifests/qotd_pdf.yaml
  demos/qotd/manifests/qotd_web.yaml
  demos/speedtest/kind/apply_policy.py
  demos/speedtest/kind/service_import.py
  demos/speedtest/kind/test.py
  demos/speedtest/testdata/policy/denyFromGw.json
  demos/speedtest/testdata/policy/denyFromGw.yaml
  demos/speedtest/testdata/policy/denyToSpeedtest.json
  demos/speedtest/testdata/policy/denyToSpeedtest.yaml
  demos/utils/cloud.py
  demos/utils/clusterlink.py
  demos/utils/common.py
  demos/utils/k8s.py
  demos/utils/kind.py
Labels: size/XXL

#448 website: Add iPerf3 tutorial
  README.md
  demos/iperf3/testdata/manifests/clusterlink/allow-policy.yaml
  demos/iperf3/testdata/manifests/clusterlink/export-iperf3.yaml
  demos/iperf3/testdata/manifests/clusterlink/import-iperf3.yaml
  demos/iperf3/testdata/manifests/clusterlink/peer-client.yaml
  demos/iperf3/testdata/manifests/clusterlink/peer-server.yaml
  website/content/en/docs/tutorials/iperf.md
Labels: size/L
