Repository clusterlink-net/clusterlink, pull requests merged in 2024-01, with the labels that each got.

#228 update website devcontainer to use features
  .devcontainer/dev/devcontainer.json
  .devcontainer/dev/post-create.sh
  .devcontainer/devcontainer.json
  .devcontainer/website/devcontainer.json
  .devcontainer/website/post-create.sh
Labels: size/M

#244 Set search placeholder (for en)
  website/i18n/en.toml
Labels: size/XS

#245 Update README.md
  README.md
Labels: size/XS

#247 Enable tagliatelle linter
  .golangci.yaml
  cmd/gwctl/config/config.go
  pkg/policyengine/PolicyDispatcher_test.go
  tests/e2e/k8s/services/iperf3/client.go
Labels: size/M

#246 ignore missing license in lock files
  .licenserc.yaml
Labels: size/XS

#253 enable whitespace linter
  .golangci.yaml
  cmd/gwctl/subcommand/gwctl.go
  pkg/k8s/kubernetes/kubeinformer.go
  pkg/platform/k8s/pod_reconciler_test.go
  pkg/utils/netutils/netutils.go
Labels: size/XS

#252 make `testpackage` linter pass
  .golangci.yaml
  pkg/platform/k8s/platform.go
  pkg/platform/k8s/pod_reconciler.go
  pkg/platform/k8s/pod_reconciler_test.go
  tests/e2e/k8s/k8s_test.go
Labels: size/M

#251 Enable `thelper` linter
  .golangci.yaml
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/loadBalancer_test.go
Labels: size/XS

#249 enable nolintlint linter
  .golangci.yaml
Labels: size/XS

#248 enable govet.fieldalignment
  .golangci.yaml
Labels: size/XS

#254 Enable additional errcheck linter options
  .golangci.yaml
  cmd/gwctl/config/config.go
  cmd/gwctl/subcommand/config.go
  pkg/controlplane/store/accesspolicies.go
  pkg/controlplane/store/bindings.go
  pkg/controlplane/store/exports.go
  pkg/controlplane/store/imports.go
  pkg/controlplane/store/lbpolicies.go
  pkg/controlplane/store/peers.go
  pkg/k8s/kubernetes/kubeinformer.go
  pkg/policyengine/connectivitypdp/connectivity_pdp.go
  pkg/util/log/log.go
  pkg/versioninfo/version.go
  tests/e2e/k8s/util/kind.go
Labels: size/L

#255 Enable `gofumpt` linter instead of `gofmt`
  .golangci.yaml
  cmd/cl-adm/cmd/create/create_fabric.go
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-dataplane/app/server.go
  cmd/cl-go-dataplane/app/server.go
  cmd/gwctl/config/config.go
  cmd/gwctl/subcommand/binding.go
  cmd/gwctl/subcommand/config.go
  cmd/gwctl/subcommand/export.go
  cmd/gwctl/subcommand/gwctl.go
  cmd/gwctl/subcommand/import.go
  pkg/controlplane/client.go
  pkg/controlplane/eventmanager/events.go
  pkg/controlplane/portmanager.go
  pkg/controlplane/xdsmanager.go
  pkg/dataplane/client/fetcher.go
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/forwarder.go
  pkg/metrics/metrics.go
  pkg/platform/k8s/platform.go
  pkg/platform/unknown/platform.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
  pkg/policyengine/policytypes/connectivity_policy_test.go
  pkg/store/kv/bolt/store.go
  pkg/util/http/server.go
  pkg/util/jsonapi/client.go
  pkg/util/log/log.go
  pkg/util/rest/server.go
  pkg/util/sniproxy/server.go
  pkg/util/tcp/listener.go
  pkg/utils/netutils/netutils.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/L

#257 Website update
  website/assets/icons/logo.svg
  website/assets/scss/_search.scss
  website/content/en/_index.md
  website/layouts/shortcodes/clusterlink/feature.html
  website/layouts/shortcodes/clusterlink/intro.html
  website/static/clusterlink_logo.png
Labels: size/L

#263 Update website colors and favicon
  website/assets/scss/_variables_project.scss
  website/content/en/_index.md
  website/layouts/partials/favicons.html
  website/layouts/shortcodes/clusterlink/card.html
  website/layouts/shortcodes/clusterlink/main.html
  website/static/clusterlink_figure.png
  website/static/clusterlink_logo.png
  website/static/favicons/favicon.ico
  website/static/favicons/favicon.png
Labels: size/M

#266 Enable `nestif` linter
  .golangci.yaml
  pkg/k8s/kubernetes/kubeinformer.go
  pkg/platform/k8s/reconciler.go
Labels: size/M

#258 Enable lll linter
  .golangci.yaml
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/gwctl/subcommand/export.go
  cmd/gwctl/subcommand/gwctl.go
  cmd/gwctl/subcommand/metrics.go
  pkg/api/types.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/authz.go
  pkg/controlplane/server/http/authz.go
  pkg/dataplane/server/dataplane.go
  pkg/dataplane/server/listener.go
  pkg/dataplane/server/server.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/connectivitypdp/connectivity_pdp.go
  pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
  pkg/policyengine/policytypes/connectivity_policy.go
Labels: size/L

#268 Enabled additional `gocritic` checks
  .golangci.yaml
  cmd/gwctl/config/config.go
  cmd/gwctl/subcommand/gwctl.go
  cmd/gwctl/subcommand/metrics.go
  pkg/k8s/kubernetes/kubeinformer.go
  pkg/metrics/metrics.go
  pkg/platform/k8s/pod_reconciler.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/connectivitypdp/connectivity_pdp.go
  pkg/policyengine/connectivitypdp/connectivity_pdp_test.go
Labels: size/M

#269 changes for gocritic linter
  .golangci.yaml
  cmd/cl-controlplane/app/server.go
  pkg/controlplane/client.go
  pkg/controlplane/instance.go
  pkg/controlplane/server/http/api.go
  pkg/dataplane/client/fetcher.go
  pkg/dataplane/server/dataplane.go
  pkg/dataplane/server/forwarder.go
  pkg/dataplane/server/listener.go
  pkg/dataplane/server/server.go
  pkg/k8s/kubernetes/kubeinformer.go
  pkg/platform/k8s/platform.go
  pkg/platform/k8s/pod_reconciler.go
  pkg/platform/k8s/pod_reconciler_test.go
  pkg/policyengine/loadBalancer.go
  pkg/store/kv/manager.go
  pkg/store/kv/store.go
  pkg/util/log/log.go
  pkg/utils/netutils/netutils.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/kind.go
Labels: size/L

#273 variable name length linting fixes
  .golangci.yaml
  cmd/cl-dataplane/app/server.go
  cmd/gwctl/config/config.go
  cmd/gwctl/subcommand/export.go
  cmd/gwctl/subcommand/import.go
  cmd/gwctl/subcommand/peer.go
  cmd/gwctl/subcommand/policy.go
  pkg/controlplane/client.go
  pkg/controlplane/xdsmanager.go
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/dataplane.go
  pkg/policyengine/policytypes/connectivity_policy_test.go
  pkg/util/log/log.go
  pkg/util/rest/server.go
  pkg/util/sniproxy/server.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/util/fabric.go
Labels: size/L

#279 Fix dependabot config for Dockerfiles
  .github/dependabot.yml
Labels: size/S

#278 Makefile: don't use source command
  Makefile
Labels: size/XS

#259 api: Introduce Clusterlink operator API.
  pkg/apis/clusterlink.net/v1alpha1/groupversion_info.go
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
Labels: size/L

#260 cmd/cl-adm: Introduce `cl-secret.yaml` and `cl-instance.yaml`
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-adm/config/config.go
  pkg/bootstrap/platform/k8s.go
Labels: size/L

#261 Makefile: Add codegen target
  Makefile
  config/operator/crds/clusterlink.net_instances.yaml
  config/operator/rbac/role.yaml
  hack/boilerplate.go.txt
Labels: size/L

#214 Policy attributes design proposal
  design-proposals/policy-attributes.md
Labels: size/L

#221 Design proposal for automating deployment via operator and CRD
  design-proposals/deployment.png
  design-proposals/project-deploymnet.md
Labels: size/L

#262 config/operator: Add operator YAMLs
  config/operator/crds/clusterlink.net_instances.yaml
  config/operator/manager/manager.yaml
  config/operator/rbac/leader_election_role.yaml
  config/operator/rbac/leader_election_role_binding.yaml
  config/operator/rbac/operator_editor_role.yaml
  config/operator/rbac/operator_viewer_role.yaml
  config/operator/rbac/role_binding.yaml
  config/operator/rbac/service_account.yaml
Labels: size/L

#274 cmd/cl-operator: Introduce the deployment operator (cl-operator).
  Makefile
  cmd/cl-operator/Dockerfile
  cmd/cl-operator/main.go
  go.mod
  go.sum
  pkg/operator/controller/instance_controller.go
Labels: size/XL
