Repository clusterlink-net/clusterlink, pull requests merged in 2024-07, with the labels that each got.

#664 Add container readiness probes
  cmd/cl-controlplane/app/server.go
  cmd/cl-dataplane/app/envoy.go
  cmd/cl-dataplane/app/envoyconf.go
  cmd/cl-dataplane/app/server.go
  cmd/cl-go-dataplane/app/server.go
  pkg/bootstrap/cert.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/api/const.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/control/manager.go
  pkg/dataplane/api/const.go
  pkg/dataplane/client/fetcher.go
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/server.go
  pkg/operator/controller/instance_controller.go
  pkg/operator/controller/instance_controller_test.go
  pkg/util/http/server.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/L

#666 tests/e2e/k8s: Fix TestOperator
  tests/e2e/k8s/test_operator.go
Labels: size/M

#669 Instance CRD: Support empty registry
  config/crds/clusterlink.net_instances.yaml
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/operator/controller/instance_controller_test.go
Labels: size/XS

#670 controlplane/authz: Use a faster JWT algorithm
  pkg/controlplane/api/authz.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/control/manager.go
Labels: enhancement, size/M, controlplane

#672 Cache TLS sessions
  pkg/dataplane/server/dataplane.go
  pkg/util/tls/util.go
Labels: size/S

#665 More Pod attributes for PDP: SA and labels
  demos/bookinfo/manifests/clusterlink/deny-server1-policy.yaml
  demos/bookinfo/test.py
  demos/speedtest/testdata/policy/denyFromGw.yaml
  demos/speedtest/testdata/policy/denyToSpeedtest.yaml
  examples/policies/allowToReviews.json
  examples/policies/deny_from_gw1.json
  pkg/controlplane/authz/connectivitypdp/connectivity_pdp.go
  pkg/controlplane/authz/connectivitypdp/connectivity_pdp_test.go
  pkg/controlplane/authz/manager.go
  tests/e2e/k8s/services/httpecho/client.go
  tests/e2e/k8s/test_policy.go
  tests/e2e/k8s/util/policies.go
  website/content/en/docs/main/tutorials/bookinfo/index.md
Labels: size/L

#673 Documenting available attributes for access policies
  website/content/en/docs/main/concepts/policies.md
Labels: size/S

#674 [FRP]: Create FRP task and demo
  demos/frp/kind/test.py
  demos/frp/test.py
  demos/frp/testdata/manifests/client/frpc.yaml
  demos/frp/testdata/manifests/client/peer1/frpc-configmap.yaml
  demos/frp/testdata/manifests/client/peer1/peer.yaml
  demos/frp/testdata/manifests/client/peer2/frpc-configmap.yaml
  demos/frp/testdata/manifests/client/peer2/peer.yaml
  demos/frp/testdata/manifests/client/peer3/frpc-configmap.yaml
  demos/frp/testdata/manifests/client/peer3/peer.yaml
  demos/frp/testdata/manifests/frp-ns.yaml
  demos/frp/testdata/manifests/server/frps-configmap.yaml
  demos/frp/testdata/manifests/server/frps.yaml
  website/content/en/docs/main/tasks/private-networks/frp-system.png
  website/content/en/docs/main/tasks/private-networks/index.md
Labels: size/XL

#678 fix notify note to look as the rest of the notes
  website/content/en/docs/main/tasks/relay/index.md
  website/content/en/docs/v0.4/tasks/relay/index.md
Labels: size/XS

#679 Setting Peer attributes - Phase 1
  cmd/cl-controlplane/app/server.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  config/crds/clusterlink.net_instances.yaml
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/authz/manager.go
  pkg/operator/controller/instance_controller.go
  tests/e2e/k8s/test_policy.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: policies, size/L
