Repository clusterlink-net/clusterlink, pull requests merged in 2024-05, with the labels that each got.

#536 README: Adding references to the website
  README.md
  docs/clusterlink.png
  docs/figures/clusterlink.png
Labels: documentation, size/M, ignore-for-release

#547 [website]: update docs to release v0.2
  website/config.toml
  website/content/en/docs/v0.1/_index.md
  website/content/en/docs/v0.1/concepts/_index.md
  website/content/en/docs/v0.1/concepts/fabric.md
  website/content/en/docs/v0.1/concepts/peers.md
  website/content/en/docs/v0.1/concepts/policies.md
  website/content/en/docs/v0.1/concepts/services.md
  website/content/en/docs/v0.1/doc-contribution/_index.md
  website/content/en/docs/v0.1/getting-started/_index.md
  website/content/en/docs/v0.1/getting-started/developers.md
  website/content/en/docs/v0.1/getting-started/users.md
  website/content/en/docs/v0.1/overview/_index.md
  website/content/en/docs/v0.1/tutorials/_index.md
  website/content/en/docs/v0.1/tutorials/iperf.md
  website/content/en/docs/v0.2/_index.md
  website/content/en/docs/v0.2/concepts/_index.md
  website/content/en/docs/v0.2/concepts/fabric.md
  website/content/en/docs/v0.2/concepts/peers.md
  website/content/en/docs/v0.2/concepts/policies.md
  website/content/en/docs/v0.2/concepts/services.md
  website/content/en/docs/v0.2/doc-contribution/_index.md
  website/content/en/docs/v0.2/getting-started/_index.md
  website/content/en/docs/v0.2/getting-started/developers.md
  website/content/en/docs/v0.2/getting-started/users.md
  website/content/en/docs/v0.2/overview/_index.md
  website/content/en/docs/v0.2/tasks/_index.md
  website/content/en/docs/v0.2/tasks/operator.md
  website/content/en/docs/v0.2/tutorials/_index.md
  website/content/en/docs/v0.2/tutorials/iperf.md
Labels: size/XXL

#552 website: publish clusterlink intro blog
  website/content/en/blog/clusterlink-intro/index.md
Labels: size/XS

#551 [website] Update markdown to use GIT tag param in release links
  hack/gen-doc-version.sh
Labels: documentation, size/S, ignore-for-release

#544 website: Add BookInfo tutorial
  demos/bookinfo/kind/README.md
  demos/bookinfo/manifests/clusterlink/allow-policy.yaml
  demos/bookinfo/manifests/clusterlink/deny-server1-policy.yaml
  demos/bookinfo/manifests/clusterlink/export-reviews.yaml
  demos/bookinfo/manifests/clusterlink/import-reviews-lb-random.yaml
  demos/bookinfo/manifests/clusterlink/import-reviews-lb-static.yaml
  demos/bookinfo/manifests/clusterlink/import-reviews.yaml
  demos/bookinfo/manifests/clusterlink/peer-client.yaml
  demos/bookinfo/manifests/clusterlink/peer-server1.yaml
  demos/bookinfo/manifests/clusterlink/peer-server2.yaml
  demos/bookinfo/manifests/review/review-v2.yaml
  demos/bookinfo/manifests/review/review-v3.yaml
  website/content/en/docs/main/tutorials/bookinfo/bookinfo.png
  website/content/en/docs/main/tutorials/bookinfo/index.md
  website/content/en/docs/main/tutorials/iperf/index.md
  website/content/en/docs/v0.2/tutorials/bookinfo/bookinfo.png
  website/content/en/docs/v0.2/tutorials/bookinfo/index.md
Labels: documentation, size/XL

#559 [website] Docs/google analytics
  website/config.toml
Labels: size/XS

#560 website: Fix tutorials link in User guide
  website/content/en/docs/main/getting-started/users.md
  website/content/en/docs/v0.1/getting-started/users.md
  website/content/en/docs/v0.2/getting-started/users.md
Labels: size/XS

#558 [website] use default named links
  website/content/en/blog/hello-world/index.md
  website/content/en/docs/main/concepts/fabric.md
  website/content/en/docs/main/concepts/peers.md
  website/content/en/docs/main/concepts/policies.md
  website/content/en/docs/main/concepts/services.md
  website/content/en/docs/main/doc-contribution/_index.md
  website/content/en/docs/main/getting-started/_index.md
  website/content/en/docs/main/getting-started/developers.md
  website/content/en/docs/main/getting-started/users.md
  website/content/en/docs/main/overview/_index.md
  website/content/en/docs/main/tasks/operator.md
  website/content/en/docs/main/tutorials/bookinfo/index.md
  website/content/en/docs/main/tutorials/iperf/index.md
Labels: documentation, size/L, ignore-for-release

#567 clusterlink deploy peer: Remove CA private keys requirement
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  pkg/bootstrap/cert.go
  pkg/bootstrap/crypt.go
Labels: size/M

#564 Create support for arm64 architecture for docker images.
  .github/workflows/release.yml
  Makefile
  cmd/cl-controlplane/Dockerfile
  cmd/cl-dataplane/Dockerfile
  cmd/cl-go-dataplane/Dockerfile
  cmd/cl-operator/Dockerfile
  demos/iperf3/cloud/test.py
  demos/iperf3/testdata/manifests/iperf3-client/iperf3-client.yaml
  demos/iperf3/testdata/manifests/iperf3-client/iperf3-client2.yaml
  demos/iperf3/testdata/manifests/iperf3-server/iperf3.yaml
  demos/utils/cloud.py
Labels: size/L

#572 website: Refining the explanation for how to create certificates
  website/content/en/docs/main/getting-started/users.md
Labels: documentation, size/S

#575 [website] Replace relative link with relref
  website/content/en/docs/main/doc-contribution/_index.md
  website/content/en/docs/main/getting-started/_index.md
  website/content/en/docs/main/overview/_index.md
  website/content/en/docs/main/tasks/operator.md
  website/content/en/docs/main/tutorials/bookinfo/index.md
  website/content/en/docs/main/tutorials/iperf/index.md
  website/content/en/docs/v0.1/doc-contribution/_index.md
  website/content/en/docs/v0.1/getting-started/_index.md
  website/content/en/docs/v0.1/overview/_index.md
  website/content/en/docs/v0.1/tutorials/iperf.md
  website/content/en/docs/v0.2/doc-contribution/_index.md
  website/content/en/docs/v0.2/getting-started/_index.md
  website/content/en/docs/v0.2/overview/_index.md
  website/content/en/docs/v0.2/tasks/operator.md
  website/content/en/docs/v0.2/tutorials/bookinfo/index.md
  website/content/en/docs/v0.2/tutorials/iperf.md
  website/netlify.toml
Labels: size/M

#534 Policy engine cleanup
  CODEOWNERS
  cmd/cl-controlplane/app/server.go
  demos/iperf3/kind/README.md
  examples/policies/allowAll.json
  examples/policies/allowToReviews.json
  examples/policies/deny_from_gw1.json
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/controlplane/authz/connectivitypdp/accesspolicy.go
  pkg/controlplane/authz/connectivitypdp/connectivity_pdp.go
  pkg/controlplane/authz/connectivitypdp/connectivity_pdp_test.go
  pkg/controlplane/authz/connectivitypdp/test_data/all_layers.yaml
  pkg/controlplane/authz/connectivitypdp/test_data/mixed_policies_and_other_resources.yaml
  pkg/controlplane/authz/connectivitypdp/test_data/not_a_yaml
  pkg/controlplane/authz/connectivitypdp/test_data/privileged_and_regular.yaml
  pkg/controlplane/authz/connectivitypdp/test_data/simple_privileged.yaml
  pkg/controlplane/authz/controllers.go
  pkg/controlplane/authz/loadbalancer.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/authz/server.go
  pkg/controlplane/control/controllers.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/peer.go
  pkg/controlplane/rest/accesspolicy.go
  pkg/controlplane/rest/export.go
  pkg/controlplane/rest/import.go
  pkg/controlplane/rest/peer.go
  pkg/controlplane/store/types.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/connectivitypdp/connection_request.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_loadbalancing.go
  tests/e2e/k8s/test_policy.go
  tests/e2e/k8s/util/clusterlink.go
  tests/k8s.sh
  website/content/en/docs/main/concepts/policies.md
Labels: size/XXL, code maintenance

#583 [website] clean and document toplevel netlify config
  netlify.toml
Labels: documentation, size/XS, ignore-for-release

#574 Fix gwctl
  cmd/gwctl/subcommand/policy.go
Labels: size/XS

#584 [website] minor edits
  website/content/en/docs/main/concepts/_index.md
  website/content/en/docs/main/concepts/fabric.md
  website/content/en/docs/main/concepts/peers.md
  website/content/en/docs/main/getting-started/developers.md
Labels: size/M

#585 tests/e2e/k8s: Fix race in peer status check
  tests/e2e/k8s/test_basic.go
Labels: size/XS

#595 Add local gateway name as attribute
  pkg/controlplane/authz/manager.go
  tests/e2e/k8s/test_policy.go
Labels: size/S

#589 Update index.md
  website/content/en/blog/clusterlink-intro/index.md
Labels: size/S

#587 Documentation tweaks
  website/content/en/blog/clusterlink-intro/index.md
  website/content/en/docs/main/concepts/fabric.md
  website/content/en/docs/main/concepts/peers.md
  website/content/en/docs/main/concepts/policies.md
  website/content/en/docs/main/doc-contribution/_index.md
  website/content/en/docs/main/getting-started/_index.md
  website/content/en/docs/main/getting-started/developers.md
  website/content/en/docs/main/getting-started/users.md
  website/content/en/docs/main/overview/_index.md
  website/content/en/docs/main/tasks/_index.md
  website/content/en/docs/main/tasks/operator.md
  website/content/en/docs/main/tutorials/bookinfo/index.md
  website/content/en/docs/main/tutorials/iperf/index.md
  website/content/en/docs/v0.1/getting-started/developers.md
  website/content/en/docs/v0.2/getting-started/developers.md
Labels: size/L

#590 Update linkcheck.yml to only run on main repo and not on forks
  .github/workflows/linkcheck.yml
Labels: size/XS, ignore-for-release

#598 One more commit - and have the other commits been applied? If not, what to do?
  website/content/en/docs/main/getting-started/users.md
Labels: size/XS

#607 Update clusterlink.py
  demos/utils/clusterlink.py
Labels: documentation, size/XS

#606 Update test.py
  demos/bookinfo/cloud/test.py
Labels: documentation, size/XS

#605 Update test.py
  demos/iperf3/test.py
Labels: documentation, size/XS

#614 Update install_clusterlink.sh
  hack/install_clusterlink.sh
Labels: size/XS

#612 Update gen-doc-version.sh
  hack/gen-doc-version.sh
Labels: size/XS, ignore-for-release

#611 Update install-devtools.sh
  hack/install-devtools.sh
Labels: size/XS, ignore-for-release

#613 Update instance_types.go
  config/crds/clusterlink.net_instances.yaml
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
Labels: size/S, ignore-for-release

#288 enable nilnil linter
  .golangci.yaml
Labels: size/XS

#609 Send attributes of source workload to remote peer
  pkg/controlplane/api/authz.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/authz/server.go
Labels: policies, size/S

#615 [website] revise About page based on intro blog
  website/content/en/about/_index.md
Labels: size/M

#618 Add import and export labels as destination attributes
  pkg/controlplane/authz/manager.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/test_policy.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/kind.go
Labels: policies, size/M

#604 Create SECURITY.md
  SECURITY.md
Labels: size/M, ignore-for-release

#617 website: Add multi-hop (relay) task
  demos/nginx/testdata/clusterlink/import-nginx-relay.yaml
  demos/nginx/testdata/clusterlink/peer-relay.yaml
  demos/nginx/testdata/nginx-relay-job.yaml
  website/content/en/docs/main/tasks/relay/index.md
  website/content/en/docs/main/tasks/relay/nginx-relay.png
  website/content/en/docs/main/tutorials/nginx/index.md
  website/static/files/tutorials/nginx/nginx-output.md
Labels: documentation, size/L

#619 TLS Refactoring
  cmd/cl-controlplane/app/server.go
  cmd/cl-dataplane/app/envoy.go
  cmd/cl-dataplane/app/envoyconf.go
  cmd/cl-dataplane/app/server.go
  cmd/cl-go-dataplane/app/server.go
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  cmd/clusterlink/config/config.go
  go.mod
  go.sum
  pkg/bootstrap/cert.go
  pkg/bootstrap/crypt.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/api/authz.go
  pkg/controlplane/api/heartbeat.go
  pkg/controlplane/api/servername.go
  pkg/controlplane/api/xds.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/authz/server.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/peer.go
  pkg/controlplane/peer/client.go
  pkg/controlplane/xds/manager.go
  pkg/controlplane/xds/server.go
  pkg/dataplane/api/servername.go
  pkg/dataplane/client/fetcher.go
  pkg/dataplane/client/xds.go
  pkg/dataplane/server/dataplane.go
  pkg/dataplane/server/listener.go
  pkg/dataplane/server/server.go
  pkg/operator/controller/instance_controller.go
  pkg/util/jsonapi/client.go
  pkg/util/sniproxy/server.go
  pkg/util/tls/util.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/test_loadbalancing.go
  tests/e2e/k8s/util/async.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
  website/content/en/docs/main/concepts/peers.md
  website/content/en/docs/main/tasks/operator.md
Labels: size/XXL

#620 website: Extend the explanation in the iperf3 tutorial
  website/content/en/docs/main/tutorials/iperf/index.md
  website/content/en/docs/main/tutorials/nginx/index.md
  website/static/files/tutorials/deploy-clusterlink.md
  website/static/files/tutorials/peer.md
Labels: documentation, size/L, ignore-for-release
