Repository clusterlink-net/clusterlink, pull requests merged in 2024-06, with the labels that each got.

#623 CLI: Enhancement for creation of ClusterLink components' certificates
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  website/content/en/docs/main/tasks/operator.md
Labels: size/L, ignore-for-release, CLI

#627 Setup Go with the Go version in go.mod
  .github/workflows/pr-check.yml
  .github/workflows/pr-e2e-test.yml
Labels: size/S

#628 nit fixes
  tests/e2e/k8s/test_loadbalancing.go
  website/content/en/docs/v0.1/concepts/policies.md
  website/content/en/docs/v0.2/concepts/policies.md
Labels: size/S

#629 cmd/cl-controlplane: Support dynamic peer certificates
  cmd/cl-controlplane/app/server.go
  go.mod
  pkg/controlplane/authz/manager.go
  pkg/controlplane/control/peer.go
  pkg/controlplane/peer/certs.go
  pkg/controlplane/xds/manager.go
  pkg/dataplane/client/xds.go
  pkg/util/runnable/manager.go
  tests/e2e/k8s/test_dynamic.go
  tests/e2e/k8s/util/clusterlink.go
Labels: size/L

#635 installation: Create a temporary directory for ClusterLink CLI installation
  hack/install_clusterlink.sh
Labels: size/S, bugfix

#634 controlplane: Change listen port number
  pkg/controlplane/api/servername.go
Labels: size/XS, bugfix

#636 website: Add description for CLI version
  .github/workflows/release.yml
  hack/install_clusterlink.sh
  website/content/en/docs/main/getting-started/users.md
Labels: size/S

#637 dataplane: Fix certificate path and listening port
  cmd/cl-controlplane/app/server.go
  cmd/cl-dataplane/app/envoyconf.go
  cmd/cl-dataplane/app/server.go
  cmd/cl-go-dataplane/app/server.go
  pkg/dataplane/api/servername.go
Labels: size/S

#638 CLI: Add zero bytes to empty certificates
  pkg/bootstrap/platform/k8s.go
Labels: size/S, ignore-for-release, CLI

#643 Update gen-doc-version.sh
  hack/gen-doc-version.sh
Labels: size/XS, ignore-for-release

#642 [website] enable and use git info for lastmod time
  website/config.toml
Labels: documentation, size/XS, ignore-for-release

#644 [website]: update docs to release v0.3
  website/config.toml
  website/content/en/docs/v0.3/_index.md
  website/content/en/docs/v0.3/concepts/_index.md
  website/content/en/docs/v0.3/concepts/fabric.md
  website/content/en/docs/v0.3/concepts/peers.md
  website/content/en/docs/v0.3/concepts/policies.md
  website/content/en/docs/v0.3/concepts/services.md
  website/content/en/docs/v0.3/doc-contribution/_index.md
  website/content/en/docs/v0.3/getting-started/_index.md
  website/content/en/docs/v0.3/getting-started/developers.md
  website/content/en/docs/v0.3/getting-started/users.md
  website/content/en/docs/v0.3/overview/_index.md
  website/content/en/docs/v0.3/tasks/_index.md
  website/content/en/docs/v0.3/tasks/operator.md
  website/content/en/docs/v0.3/tasks/relay/index.md
  website/content/en/docs/v0.3/tasks/relay/nginx-relay.png
  website/content/en/docs/v0.3/tutorials/_index.md
  website/content/en/docs/v0.3/tutorials/bookinfo/bookinfo.png
  website/content/en/docs/v0.3/tutorials/bookinfo/index.md
  website/content/en/docs/v0.3/tutorials/iperf/index.md
  website/content/en/docs/v0.3/tutorials/nginx/index.md
Labels: size/XXL

#645 controlplane: Add error message when hearbeat fail.
  pkg/controlplane/control/peer.go
Labels: size/XS

#646 website: Fix allow-all-policy.md
  website/content/en/docs/main/tutorials/iperf/index.md
  website/content/en/docs/main/tutorials/nginx/index.md
  website/content/en/docs/v0.3/tutorials/iperf/index.md
  website/content/en/docs/v0.3/tutorials/nginx/index.md
  website/static/files/tutorials/allow-all-policy.md
Labels: size/L

#647 Website: Add explanation on merge functionality in imports
  website/content/en/docs/main/concepts/services.md
  website/go.mod
  website/go.sum
Labels: size/M

#657 controlplane: Use leader election for control controllers
  cmd/cl-controlplane/app/server.go
  config/operator/rbac/role.yaml
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/control/controllers.go
  pkg/operator/controller/instance_controller.go
  pkg/util/controller/controller.go
Labels: size/M, controlplane

#654 controlplane: Store JWK keys in k8s secret
  cmd/cl-controlplane/app/server.go
  config/operator/rbac/role.yaml
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/authz/controllers.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/control/controllers.go
  pkg/controlplane/control/manager.go
  pkg/operator/controller/instance_controller.go
Labels: size/L, controlplane

#662 golangci: Fix format warning
  .golangci.yaml
  pkg/controlplane/control/manager.go
Labels: size/XS

#651 .github/workflows: Add CLI installation checks.
  .github/workflows/pr-cli.yml
  tests/cli/basic_test.sh
Labels: size/L

#659 Support multiple controlplane replicas
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/test_redundancy.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/M
