Repository clusterlink-net/clusterlink, pull requests merged in 2024-02, with the labels that each got.

#298 Makefile: Add gofumpt
  Makefile
  hack/install-devtools.sh
Labels: size/S

#300 policyengine: AddBinding should not error
  pkg/controlplane/instance.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
Labels: size/S

#303 pkg/util: Some refactoring
  cmd/cl-controlplane/app/server.go
  cmd/cl-dataplane/app/server.go
  cmd/cl-go-dataplane/app/server.go
  cmd/gwctl/config/config.go
  cmd/gwctl/subcommand/gwctl.go
  pkg/controlplane/instance.go
  pkg/dataplane/server/dataplane.go
  pkg/dataplane/server/server.go
  pkg/platform/k8s/platform.go
  pkg/util/log/util.go
  pkg/util/net/util.go
  pkg/util/tls/util.go
  pkg/utils/netutils/netutils.go
Labels: size/L

#304 controlplane: Add CRD mode flag
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-controlplane/app/server.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/S

#309 pkg/bootstrap: Add ingressType and namespace to config
  cmd/cl-adm/cmd/create/create_peer.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  tests/e2e/k8s/util/k8s_yaml.go
Labels: size/M

#301 Prepare for import/export namespace support
  cmd/cl-dataplane/app/envoy.go
  cmd/cl-dataplane/app/envoyconf.go
  pkg/controlplane/api/authz.go
  pkg/controlplane/api/xds.go
  pkg/controlplane/authz.go
  pkg/controlplane/server/http/authz.go
  pkg/controlplane/xdsmanager.go
  pkg/dataplane/server/listener.go
  pkg/policyengine/policytypes/connection_request.go
Labels: size/L

#287 Design for CRD based management
  design-proposals/crd-based-management.md
Labels: size/L

#312 bootstrap/platform/k8s: Fix CRD-mode yaml
  pkg/bootstrap/platform/k8s.go
Labels: size/S

#313 cl-controlplane: Changes to namespace env variable
  cmd/cl-adm/cmd/create/create_peer.go
  cmd/cl-controlplane/app/server.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/instance.go
  pkg/operator/controller/instance_controller.go
  pkg/platform/k8s/platform.go
Labels: size/M

#317 cl-dataplane: Add app name constant
  cmd/cl-dataplane/app/server.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/instance.go
  pkg/operator/controller/instance_controller.go
Labels: size/S

#302 docs/getting-started: Update the getting-started document
  website/content/en/docs/getting-started/_index.md
Labels: size/M

#318 demos/utils: fix deployment to run on default namespace
  demos/iperf3/kind/README.md
  demos/utils/common.py
  docs/installation.md
Labels: size/S

#315 operator/controller: Handle more than one instance in the same namespace
  cmd/cl-operator/main.go
  config/operator/crds/clusterlink.net_instances.yaml
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/operator/controller/instance_controller.go
Labels: size/L

#306 controlplane: Refactor servers
  cmd/cl-controlplane/app/server.go
  pkg/controlplane/authz/server.go
  pkg/controlplane/rest/accesspolicy.go
  pkg/controlplane/rest/binding.go
  pkg/controlplane/rest/export.go
  pkg/controlplane/rest/import.go
  pkg/controlplane/rest/lbpolicy.go
  pkg/controlplane/rest/peer.go
  pkg/controlplane/rest/server.go
  pkg/controlplane/server/http/api.go
  pkg/controlplane/server/http/heartbeat.go
  pkg/controlplane/server/http/server.go
  pkg/controlplane/xds/server.go
  pkg/util/grpc/server.go
  pkg/util/rest/server.go
Labels: size/XXL

#314 tests/e2e: Add support to create cluster with operator
  cmd/cl-adm/cmd/create/create_peer.go
  pkg/bootstrap/platform/k8s.go
  pkg/operator/controller/instance_controller.go
  tests/e2e/k8s/suite.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/k8s_yaml.go
  tests/e2e/k8s/util/kind.go
Labels: size/L

#299 apis: Add Export, Import, Peer, AccessPolicy CRDs
  Makefile
  config/crds/clusterlink.net_accesspolicies.yaml
  config/crds/clusterlink.net_exports.yaml
  config/crds/clusterlink.net_imports.yaml
  config/crds/clusterlink.net_instances.yaml
  config/crds/clusterlink.net_peers.yaml
  pkg/apis/clusterlink.net/v1alpha1/accesspolicy.go
  pkg/apis/clusterlink.net/v1alpha1/export.go
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/apis/clusterlink.net/v1alpha1/peer.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
  tests/e2e/k8s/suite.go
Labels: size/XL

#321 tests/e2e: Introduce new e2e operator test
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/kind.go
Labels: size/L

#323 controlplane/xds: Introduce Manager
  cmd/cl-controlplane/app/server.go
  pkg/controlplane/instance.go
  pkg/controlplane/xds/manager.go
  pkg/controlplane/xds/server.go
Labels: size/L

#325 controlplane: Introduce control package
  cmd/cl-controlplane/app/server.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/portmanager.go
  pkg/controlplane/instance.go
  pkg/operator/controller/instance_controller.go
  pkg/platform/k8s/platform.go
  pkg/platform/k8s/reconciler.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/test_operator.go
  tests/e2e/k8s/test_performance.go
Labels: size/XL

#295 operator/controller: Add controller unit test
  .devcontainer/dev/post-create.sh
  Makefile
  hack/install-devtools.sh
  pkg/operator/controller/instance_controller.go
  pkg/operator/controller/instance_controller_test.go
Labels: size/L

#327 Adding comments to various fields in AccessPolicy
  config/crds/clusterlink.net_accesspolicies.yaml
  pkg/apis/clusterlink.net/v1alpha1/accesspolicy.go
Labels: size/M

#352 tests/e2e: Add wait condition to operator test
  tests/e2e/k8s/test_operator.go
Labels: size/M

#328 controlplane: Introduce authz package
  cmd/cl-controlplane/app/server.go
  go.mod
  go.sum
  pkg/controlplane/api/authz.go
  pkg/controlplane/authz.go
  pkg/controlplane/authz/controllers.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/authz/server.go
  pkg/controlplane/instance.go
  pkg/controlplane/peer/client.go
  pkg/platform/k8s/platform.go
  pkg/platform/k8s/pod_reconciler.go
  pkg/platform/k8s/pod_reconciler_test.go
  tests/e2e/k8s/test_basic.go
Labels: size/XXL

#356 Set release path in URL
  website/content/en/docs/getting-started/_index.md
Labels: size/XS

#355 Fix cl-go-dataplane image path
  pkg/bootstrap/platform/k8s.go
Labels: size/XS

#358 replaced references with overview section
  website/content/en/_index.md
  website/content/en/docs/reference/_index.md
Labels: size/S

#347 controlplane/control: Support port updates
  cmd/cl-controlplane/app/server.go
  config/crds/clusterlink.net_imports.yaml
  config/operator/rbac/role.yaml
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/port.go
  pkg/operator/controller/instance_controller.go
Labels: size/L

#354 Elaborate the core concepts documentation
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/site.md
  website/content/en/docs/concepts/sites.md
  website/content/en/docs/tutorials/iperf.md
Labels: documentation, size/L

#362 use hugo ref for linking
  website/content/en/_index.md
  website/content/en/about/_index.md
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/sites.md
  website/content/en/docs/doc-contribution/_index.md
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/overview/_index.md
Labels: size/M

#365 [docs] Add notice module and notices for site creation
  website/content/en/docs/concepts/sites.md
  website/go.mod
  website/go.sum
  website/hugo.toml
Labels: documentation, size/M
