Repository clusterlink-net/clusterlink, pull requests merged in 2024-04, with the labels that each got.

#472 [website] update blog: first release is 0.1.0 not 0.2.0
  website/content/en/blog/hello-world/index.md
Labels: size/XS, ignore-for-release

#474 policyengine/examples: Fix JSONs' policy to support policy CRD.
  pkg/policyengine/examples/allowAll.json
  pkg/policyengine/examples/allowToReviews.json
  pkg/policyengine/examples/deny_from_gw1.json
Labels: size/S

#469 [website] Service sharing concept documentation
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/peers.md
  website/content/en/docs/concepts/policies.md
  website/content/en/docs/concepts/services.md
Labels: size/L

#476 Documentation for access policies
  website/content/en/docs/concepts/policies.md
Labels: size/L

#475 website: nit fixes
  website/Makefile
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/peers.md
  website/content/en/docs/concepts/policies.md
  website/content/en/docs/concepts/services.md
  website/content/en/docs/getting-started/developers.md
  website/content/en/docs/getting-started/users.md
  website/content/en/docs/overview/_index.md
  website/content/en/docs/tutorials/iperf.md
Labels: documentation, size/L

#477 tutorials/iperf3: Fix URLpath.
  website/content/en/docs/tutorials/iperf.md
Labels: size/M

#484 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#488 pkg/apis: Validate import names
  .github/ISSUE_TEMPLATE/config.yml
  config/crds/clusterlink.net_imports.yaml
  pkg/apis/clusterlink.net/v1alpha1/import.go
  tests/e2e/k8s/test_import.go
  tests/e2e/k8s/util/kind.go
Labels: size/M, bugfix

#489 Create config.yml to control issue templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: size/XS

#480 .github/release: Add automatically generated release notes yaml
  .github/release.yml
Labels: size/S, ignore-for-release

#491 Remove duplicated text in README
  README.md
Labels: size/XS

#487 [Feature]: go1.22 support
  .devcontainer/dev/post-create.sh
  .github/workflows/pr-check.yml
  .github/workflows/pr-e2e-test.yml
  Containerfile.dev
  Makefile
  README.md
  config/crds/clusterlink.net_accesspolicies.yaml
  config/crds/clusterlink.net_exports.yaml
  config/crds/clusterlink.net_imports.yaml
  config/crds/clusterlink.net_instances.yaml
  config/crds/clusterlink.net_peers.yaml
  config/crds/clusterlink.net_privilegedaccesspolicies.yaml
  go.mod
  go.sum
Labels: enhancement, size/XL

#494 [website] different logo color schemes
  website/static/logo-darkblue-yellow.png
  website/static/logo-lightblue-yellow.png
  website/static/logo-white-yellow.png
Labels: size/XS, ignore-for-release

#497 operator/controller: Remove PVC from the operator.
  config/operator/rbac/role.yaml
  pkg/operator/controller/instance_controller.go
  pkg/operator/controller/instance_controller_test.go
Labels: size/M, operator

#499 docs/getting-started: update the uninstall section
  website/content/en/docs/getting-started/users.md
Labels: documentation, size/S

#498 demos: Fix the BookInfo demo and add support to AWS in the demo environment
  demos/bookinfo/cloud/apply_lb.py
  demos/bookinfo/cloud/gw_failover.py
  demos/bookinfo/cloud/test.py
  demos/bookinfo/kind/apply_lb.py
  demos/bookinfo/manifests/product/details.yaml
  demos/bookinfo/manifests/product/kind-config.yaml
  demos/bookinfo/manifests/product/product.yaml
  demos/bookinfo/manifests/product/product2.yaml
  demos/bookinfo/manifests/product/review-svc.yaml
  demos/bookinfo/manifests/review/kind-config.yaml
  demos/bookinfo/manifests/review/rating.yaml
  demos/bookinfo/manifests/review/review-v2.yaml
  demos/bookinfo/manifests/review/review-v3.yaml
  demos/bookinfo/test.py
  demos/iperf3/cloud/test.py
  demos/utils/cloud.py
  demos/utils/clusterlink.py
  demos/utils/k8s.py
Labels: size/L, ignore-for-release, demos

#496 cmd/clusterlink: import oidc to client-go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
Labels: size/XS, ignore-for-release, CLI

#504 [website] Minor indentation and wording changes
  website/content/en/about/_index.md
  website/content/en/docs/_index.md
  website/content/en/docs/concepts/fabric.md
  website/content/en/docs/concepts/peers.md
  website/content/en/docs/concepts/policies.md
  website/content/en/docs/concepts/services.md
  website/content/en/docs/getting-started/developers.md
  website/content/en/docs/getting-started/users.md
  website/content/en/docs/tutorials/iperf.md
Labels: documentation, size/L, ignore-for-release

#505 website/content: update Concepts' YAML files
  website/content/en/docs/concepts/peers.md
  website/content/en/docs/concepts/policies.md
  website/content/en/docs/concepts/services.md
  website/content/en/docs/getting-started/users.md
  website/static/files/peer_crd_sample.yaml
Labels: documentation, size/L

#511 Makefile: Fix version info flags in docker images
  Makefile
Labels: size/S

#512 hack/install-devtools.sh: Update versions
  .devcontainer/dev/devcontainer.json
  .devcontainer/dev/post-create.sh
  hack/install-devtools.sh
Labels: size/S

#492 pkg/api: Cleanup
  cmd/gwctl/subcommand/policy.go
  pkg/api/types.go
  pkg/client/client.go
  pkg/controlplane/authz/manager.go
  pkg/controlplane/rest/accesspolicy.go
  pkg/controlplane/rest/lbpolicy.go
  pkg/controlplane/rest/manager.go
  pkg/controlplane/rest/server.go
  pkg/controlplane/store/lbpolicies.go
  pkg/controlplane/store/types.go
  pkg/policyengine/PolicyDispatcher.go
  pkg/policyengine/PolicyDispatcher_test.go
  pkg/policyengine/loadBalancer.go
  pkg/policyengine/loadBalancer_test.go
  tests/e2e/k8s/test_basic.go
  tests/e2e/k8s/util/clusterlink.go
Labels: size/XL, code maintenance

#513 Update docs with the availability of PrivilegedAccessPolicy
  website/content/en/blog/hello-world/index.md
  website/content/en/docs/concepts/policies.md
Labels: documentation, size/S

#514 website: Add manual deployment section
  website/content/en/docs/tasks/operator.md
Labels: documentation, size/M

#516 Disable GitInfo on production deployment
  website/Makefile
  website/config.toml
Labels: size/XS

#518 fix typo in website doc
  website/config.toml
Labels: size/XS

#446 Support creating EndpointSlice while importing service
  cmd/cl-controlplane/app/server.go
  cmd/gwctl/subcommand/import.go
  config/operator/rbac/role.yaml
  pkg/apis/clusterlink.net/v1alpha1/import.go
  pkg/bootstrap/platform/k8s.go
  pkg/controlplane/control/controllers.go
  pkg/controlplane/control/manager.go
  pkg/controlplane/control/port.go
  pkg/controlplane/rest/import.go
  pkg/controlplane/store/types.go
  pkg/operator/controller/instance_controller.go
  tests/e2e/k8s/services/httpecho/client.go
  tests/e2e/k8s/test_import.go
  tests/e2e/k8s/util/clusterlink.go
  tests/e2e/k8s/util/fabric.go
  tests/e2e/k8s/util/kind.go
Labels: size/XL

#523 controlplane/peer/client: Issue requests in parallel
  pkg/controlplane/peer/client.go
  tests/e2e/k8s/test_peer.go
Labels: size/M

#524 Add Maintainers and default code owners
  .licenserc.yaml
  CODEOWNERS
  GOVERNANCE.md
  MAINTAINERS.md
Labels: size/S

#530 cmd/clusterlink: add ingress-annotations flag
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  config/crds/clusterlink.net_instances.yaml
  demos/utils/clusterlink.py
  pkg/apis/clusterlink.net/v1alpha1/instance_types.go
  pkg/apis/clusterlink.net/v1alpha1/zz_generated.deepcopy.go
  pkg/bootstrap/platform/config.go
  pkg/bootstrap/platform/k8s.go
  pkg/operator/controller/instance_controller.go
  pkg/operator/controller/instance_controller_test.go
  website/content/en/docs/tasks/operator.md
Labels: size/M, CLI

#528 Changes to support documentation versioning
  website/config.toml
  website/content/en/_index.md
  website/content/en/docs/_index.md
  website/content/en/docs/getting-started/_index.md
  website/content/en/docs/main/_index.md
  website/content/en/docs/main/concepts/_index.md
  website/content/en/docs/main/concepts/fabric.md
  website/content/en/docs/main/concepts/peers.md
  website/content/en/docs/main/concepts/policies.md
  website/content/en/docs/main/concepts/services.md
  website/content/en/docs/main/doc-contribution/_index.md
  website/content/en/docs/main/getting-started/_index.md
  website/content/en/docs/main/getting-started/developers.md
  website/content/en/docs/main/getting-started/users.md
  website/content/en/docs/main/overview/_index.md
  website/content/en/docs/main/tasks/_index.md
  website/content/en/docs/main/tasks/operator.md
  website/content/en/docs/main/tutorials/_index.md
  website/content/en/docs/main/tutorials/iperf.md
  website/content/en/docs/v0.1.0/_index.md
  website/content/en/docs/v0.1.0/concepts/_index.md
  website/content/en/docs/v0.1.0/concepts/fabric.md
  website/content/en/docs/v0.1.0/concepts/peers.md
  website/content/en/docs/v0.1.0/concepts/policies.md
  website/content/en/docs/v0.1.0/concepts/services.md
  website/content/en/docs/v0.1.0/doc-contribution/_index.md
  website/content/en/docs/v0.1.0/getting-started/_index.md
  website/content/en/docs/v0.1.0/getting-started/developers.md
  website/content/en/docs/v0.1.0/getting-started/users.md
  website/content/en/docs/v0.1.0/overview/_index.md
  website/content/en/docs/v0.1.0/tutorials/_index.md
  website/content/en/docs/v0.1.0/tutorials/iperf.md
  website/layouts/shortcodes/clusterlink/card.html
  website/layouts/shortcodes/clusterlink/intro.html
  website/layouts/shortcodes/clusterlink/main.html
Labels: documentation, size/XXL

#507 cmd/clusterlink: Move file creation to deploy command
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/delete/delete_peer.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  demos/utils/cloud.py
  demos/utils/clusterlink.py
  demos/utils/kind.py
  pkg/bootstrap/cert.go
  website/content/en/docs/main/concepts/peers.md
  website/content/en/docs/main/getting-started/users.md
  website/content/en/docs/main/tasks/operator.md
  website/content/en/docs/main/tutorials/iperf.md
Labels: size/L, ignore-for-release, CLI

#519 Introducing ClusterLink blog
  website/content/en/blog/clusterlink-intro/field.jpg
  website/content/en/blog/clusterlink-intro/index.md
Labels: size/L, ignore-for-release

#535 cmd/clusterlink: Fix path flag
  cmd/clusterlink/cmd/create/create_fabric.go
  cmd/clusterlink/cmd/create/create_peer.go
  cmd/clusterlink/cmd/deploy/deploy_peer.go
  cmd/clusterlink/config/config.go
Labels: size/M

#541 .github/workflows: Add release support to linux/arm64 platform
  .github/workflows/release.yml
Labels: size/XS

#540 Automation script to generate new docs version
  Makefile
  hack/gen-doc-version.sh
  website/config.toml
Labels: size/L

#538 Enable fetching all tags in actions/checkout
  .github/workflows/codeql.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-e2e-test.yml
  .github/workflows/release.yml
Labels: size/XS

#545 [website]: add netlify _redirects file
  .licenserc.yaml
  website/config.toml
  website/layouts/index.redirects
Labels: documentation, size/S, ignore-for-release
